[
{"content":{"body":"https://blog.cloudflare.com/improving-web-standards-urlpattern","m.mentions":{},"msgtype":"m.text"},"ts":1742822003869,"senderName":"Yagiz Nizipli","senderId":"@yagiznizipli:matrix.org","id":"$8BwcbR0RymbNQIhSEXvZXwaW_52wlAeUR17cWNxRqxU"},
{"content":{"body":"hi all! i'm working with fetch keepalive and noticed the spec doesn't provide the user with a clear reason why the request returned a NetworkError. the spec at https://fetch.spec.whatwg.org/#http-network-or-cache-fetch describes if the 64kib limit is exceeded, a \"NetworkError\" should be returned, but that prevents any kind of reasonable error handling regarding the business code. the sending party could simply try again later, when the fetchGroup is empty again or there's enough space left, but since they don't know the _reason_, it might as well be a non-recoverable error and retrying won't bring any better results. does that make sense? is this the right place to discuss this? ðŸ˜…","format":"org.matrix.custom.html","formatted_body":"hi all! i'm working with fetch keepalive and noticed the spec doesn't provide the user with a clear reason why the request returned a NetworkError. the spec at https://fetch.spec.whatwg.org/#http-network-or-cache-fetch describes if the 64kib limit is exceeded, a \"NetworkError\" should be returned, but that prevents any kind of reasonable error handling regarding the business code. the sending party could simply try again later, when the fetchGroup is empty again or there's enough space left, but since they don't know the <em>reason</em>, it might as well be a non-recoverable error and retrying won't bring any better results. does that make sense? is this the right place to discuss this? ðŸ˜…","m.mentions":{},"msgtype":"m.text"},"ts":1742830341167,"senderName":"gernknod","senderId":"@gernknod:matrix.org","id":"$X-8CKp_7OG05otFdNS5GFj4vT1rcsHU1IWUYqXs2Zpo"}
]