<!DOCTYPE html><html><head>
  <title>TC39 General on 2021-12-16</title>
  <link rel="stylesheet" href="../style.css">
  <script>window.room = "TC39 General";</script><script src="../render-roomlist.js"></script>
  <script src="../logs.js"></script>
</head>
<body><div class="wrapper">
<div class="sidebar">
<div class="title">TC39 General<br>2021-12-16<br><a href="plaintext/">plaintext logs</a></div>
<div class="nav">
<a href="2021-12-15" class="nav-link"><span>prev</span></a>
<span style="float:right">next</span>
</div>
    <div class="all-rooms"><noscript>JavaScript is required to load the channel index, but you can go to <a href="../..">the static index</a> directly.</noscript></div>
<div class="footer"><a href="https://github.com/bakkot/matrix-archive-bot">source on github</a></div>
</div>
<div class="rhs">
<div class="rhs-header">
<span id="error" style="color: red; display:none">error</span>
<input type="text" id="query" size="25" placeholder="Search TC39 General">
<a id="search-submit" class="button icon-link" title="Search">
  <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path></svg>
</a>
</div>

<div class="log"><table id="log-table"><tbody id="log-tbody">

  <tr class="msg" id="L0"><td class="ts-cell"><a class="ts" href="#L0" alt="Wed Dec 15 2021 19:17:54 GMT-0800 (Pacific Standard Time)">03:17</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@jschoi:matrix.org">jschoi</span>&gt;</div></td><td class="msg-cell">Is there a particular reason why Array.from (<a href="https://tc39.es/ecma262/#sec-cma262/#sec-call">https://tc39.es/ecma262/#sec-cma262/#sec-call</a>) seems to call CloseIterator if an error occurs when setting <code>A</code>’s properties, when there are too many items, and when <code>mapfn</code> throws an error—but not when IteratorStep results in an abrupt completion nor when the iterator depletes its items?</td></tr>
  <tr class="msg" id="L1"><td class="ts-cell"><a class="ts" href="#L1" alt="Wed Dec 15 2021 20:12:42 GMT-0800 (Pacific Standard Time)">04:12</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@bakkot:matrix.org">bakkot</span>&gt;</div></td><td class="msg-cell">we don't close the iterator when an error occurs in the iterator itself, because the iterator is broken</td></tr>
  <tr class="msg" id="L2"><td class="ts-cell"><a class="ts" href="#L2" alt="Wed Dec 15 2021 20:12:52 GMT-0800 (Pacific Standard Time)">04:12</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@bakkot:matrix.org">bakkot</span>&gt;</div></td><td class="msg-cell">and we don't close iterators when they are depleted in general</td></tr>
  <tr class="msg" id="L3"><td class="ts-cell"><a class="ts" href="#L3" alt="Wed Dec 15 2021 20:13:14 GMT-0800 (Pacific Standard Time)">04:13</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@bakkot:matrix.org">bakkot</span>&gt;</div></td><td class="msg-cell">(the assumption is that it does its own cleanup before returning <code>{done: true}</code>)</td></tr>
  <tr class="msg" id="L4"><td class="ts-cell"><a class="ts" href="#L4" alt="Wed Dec 15 2021 20:13:50 GMT-0800 (Pacific Standard Time)">04:13</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@bakkot:matrix.org">bakkot</span>&gt;</div></td><td class="msg-cell">we only call IteratorClose when we need to close an iterator because we can no longer consume it for reasons of our own</td></tr>
  <tr class="msg" id="L5"><td class="ts-cell"><a class="ts" href="#L5" alt="Wed Dec 15 2021 21:19:50 GMT-0800 (Pacific Standard Time)">05:19</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@jschoi:matrix.org">jschoi</span>&gt;</div></td><td class="msg-cell">I see. I also see you’ve posted <a href="https://github.com/tc39/rationale/issues/2">https://github.com/tc39/rationale/issues/2</a>. Thank you for both that and the explanation.</td></tr>
  <tr class="msg" id="L6"><td class="ts-cell"><a class="ts" href="#L6" alt="Wed Dec 15 2021 22:13:37 GMT-0800 (Pacific Standard Time)">06:13</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@jschoi:matrix.org">jschoi</span>&gt;</div></td><td class="msg-cell"><a href="https://github.com/tc39/proposal-array-from-async/issues/16#issuecomment-995453541">https://github.com/tc39/proposal-array-from-async/issues/16#issuecomment-995453541</a><br>As far as I can tell, there is no way to capture all possible rejections from a sync iterable’s yielded promises, while still maintaining <code>for await</code> semantics. This is correct, right?</td></tr>
  <tr class="msg" id="L7"><td class="ts-cell"><a class="ts" href="#L7" alt="Thu Dec 16 2021 09:54:07 GMT-0800 (Pacific Standard Time)">17:54</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@mhofman:matrix.org">Mathieu Hofman</span>&gt;</div></td><td class="msg-cell">What does <code>for await (const foo of iterableYieldingPromises)</code> do in this case?</td></tr>
  <tr class="msg" id="L8"><td class="ts-cell"><a class="ts" href="#L8" alt="Thu Dec 16 2021 09:55:54 GMT-0800 (Pacific Standard Time)">17:55</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@mhofman:matrix.org">Mathieu Hofman</span>&gt;</div></td><td class="msg-cell">If I was to implement this in a polyfill, I'd setup a dummy <code>.catch()</code> on the next promise to avoid the unhandled error, but still yield the original promise later</td></tr>
  <tr class="msg" id="L9"><td class="ts-cell"><a class="ts" href="#L9" alt="Thu Dec 16 2021 09:56:47 GMT-0800 (Pacific Standard Time)">17:56</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@mhofman:matrix.org">Mathieu Hofman</span>&gt;</div></td><td class="msg-cell">It's a pretty common occurrence when parallelizing async operations</td></tr>
  <tr class="msg" id="L10"><td class="ts-cell"><a class="ts" href="#L10" alt="Thu Dec 16 2021 10:00:22 GMT-0800 (Pacific Standard Time)">18:00</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-2" title="@mhofman:matrix.org">Mathieu Hofman</span>&gt;</div></td><td class="msg-cell"><mx-reply><blockquote> What does <code>for await (const foo of iterableYieldingPromises)</code> do in this case?</blockquote></mx-reply>My bad I didn't read the OP. It goes unhandled! Wondering if it's something we should fix in the language. I suppose the problem is that if the loop body throws in an error during processing of the second element, then the IteratorClose has no way to report the error. Maybe recreating a promise resolved with the rejection to trigger a future unhandled error would work</td></tr>

</tbody></table></div></div></div>
</body></html>