[
{"content":{"body":"tbh i'd say that if the catch is in a separate file from the finally, then the finally file probably shouldn't be assuming the promise is handled","msgtype":"m.text"},"ts":1686619003827,"senderName":"ljharb","senderId":"@ljharb:matrix.org","id":"$nJ0A8LV1rCRiNVRRGHqGAldj4ofRhtiUcP7a-Abpgjg"},
{"content":{"body":" * tbh i'd say that if the catch is in a separate file from the finally, then the finally file probably shouldn't be assuming the promise is handled - iow, the author of one file shouldn't assume knowledge of the code in another one","m.new_content":{"body":"tbh i'd say that if the catch is in a separate file from the finally, then the finally file probably shouldn't be assuming the promise is handled - iow, the author of one file shouldn't assume knowledge of the code in another one","msgtype":"m.text"},"m.relates_to":{"event_id":"$nJ0A8LV1rCRiNVRRGHqGAldj4ofRhtiUcP7a-Abpgjg","rel_type":"m.replace"},"msgtype":"m.text"},"ts":1686619021358,"senderName":"ljharb","senderId":"@ljharb:matrix.org","id":"$5RQHIuBQvlOmChbKNzhFBnNatHK--UvrNSd23ZCUo54"}
]