[
{"content":{"body":"Hi, what's the difference between Completion Record `normal` and `return` type?","format":"org.matrix.custom.html","formatted_body":"Hi, what's the difference between Completion Record <code>normal</code> and <code>return</code> type?","msgtype":"m.text"},"ts":1694613134037,"senderName":"zacque","senderId":"@zacque:matrix.org","id":"$IIlLiIwQZETwTHqyZwWefAFRvQ61UFK-6zTs18Jcm4E"},
{"content":{"body":"https://tc39.es/ecma262/#table-completion-record-fields","msgtype":"m.text"},"ts":1694613217088,"senderName":"zacque","senderId":"@zacque:matrix.org","id":"$VmJ1PDpxFAJ4qTyNngRhbG607yVyiq8AFJ8lgsA47_8"},
{"content":{"body":"If you evaluate a statement (within a function body, say), and it causes a return from that function, then that's signaled via a `return` completion. If evaluation is to proceed normally to the next statement, then that's signaled by a `normal` completion.","format":"org.matrix.custom.html","formatted_body":"If you evaluate a statement (within a function body, say), and it causes a return from that function, then that's signaled via a <code>return</code> completion. If evaluation is to proceed normally to the next statement, then that's signaled by a <code>normal</code> completion.","msgtype":"m.text"},"ts":1694613401097,"senderName":"jmdyck","senderId":"@jmdyck:matrix.org","id":"$dgceRGD-0aNSn3uZWAjM-IjMHtogveiomEbTMMataNA"},
{"content":{"body":"Makes sense, but what about the next paragraph: \"Callable objects that are defined in this specification only return a normal completion or a throw completion. Returning any other kind of Completion Record is considered an editorial error.\"","msgtype":"m.text"},"ts":1694613639083,"senderName":"zacque","senderId":"@zacque:matrix.org","id":"$71QMah51HX0ckHMWEN8ObfDmw7OdZCf98pd1D0Ro1os"},
{"content":{"body":"I'll expect it to include `return` completion?","format":"org.matrix.custom.html","formatted_body":"I'll expect it to include <code>return</code> completion?","msgtype":"m.text"},"ts":1694613655657,"senderName":"zacque","senderId":"@zacque:matrix.org","id":"$EWqWjpDmFL8I5jXAyDE_OY83rVSRlRS54USuL8FsxJc"},
{"content":{"body":"No, if, within function A, you call function B, that call cannot cause a return from function A. (But it can cause A to throw.)","msgtype":"m.text"},"ts":1694613765717,"senderName":"jmdyck","senderId":"@jmdyck:matrix.org","id":"$tbXNupqMhahYtrbcfWWFCBidIWrUdzjfcDAfAzyJeMA"}
]