<!DOCTYPE html><html><head>
  <title>TC39 Async Context on 2024-05-28</title>
  <link rel="stylesheet" href="../style.css">
  <script>window.room = "TC39 Async Context";</script><script src="../render-roomlist.js"></script>
  <script src="../logs.js"></script>
</head>
<body><div class="wrapper">
<div class="sidebar">
<div class="title">TC39 Async Context<br>2024-05-28<br><a href="plaintext/">plaintext logs</a></div>
<div class="nav">
<a href="2024-05-27" class="nav-link"><span>prev</span></a>
<span style="float:right">next</span>
</div>
    <div class="all-rooms"><noscript>JavaScript is required to load the channel index, but you can go to <a href="../..">the static index</a> directly.</noscript></div>
<div class="footer"><a href="https://github.com/bakkot/matrix-archive-bot">source on github</a></div>
</div>
<div class="rhs">
<div class="rhs-header">
<span id="error" style="color: red; display:none">error</span>

<input type="text" id="query" size="25" placeholder="Search TC39 Async Context">
<a id="search-submit" class="button icon-link" title="Search">
  <svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path></svg>
</a>
</div>

<div class="log"><table id="log-table"><tbody id="log-tbody">

  <tr class="msg" id="L0"><td class="ts-cell"><a class="ts" href="#L0" alt="Tue May 28 2024 02:46:20 GMT-0700 (Pacific Daylight Time)">09:46</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-4" title="@abotella:igalia.com">Andreu Botella</span>&gt;</div></td><td class="msg-cell"><mx-reply><blockquote> A single promise could be branched multiple times, and <code>unhandledrejection</code> events are dispatched for each "unhandled" promise, rather than a single source of rejection</blockquote></mx-reply>I don't think this is a problem. Context splits are not problematic, only merges are. If you only care about one of the branched promises but not the rest, you could still want to know the source of rejection</td></tr>
  <tr class="msg" id="L1"><td class="ts-cell"><a class="ts" href="#L1" alt="Tue May 28 2024 02:47:41 GMT-0700 (Pacific Daylight Time)">09:47</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-4" title="@abotella:igalia.com">Andreu Botella</span>&gt;</div></td><td class="msg-cell">the way I think of it, if an exception (or promise rejection) is "automatically rethrown" (as might happen conceptually in <code>run</code>), then if you have a way to act on that error, then that context shouldn't be lost without a trace</td></tr>
  <tr class="msg" id="L2"><td class="ts-cell"><a class="ts" href="#L2" alt="Tue May 28 2024 02:48:20 GMT-0700 (Pacific Daylight Time)">09:48</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-4" title="@abotella:igalia.com">Andreu Botella</span>&gt;</div></td><td class="msg-cell">if you choose to catch an exception/rejection and rethrow it, then you might choose to use the original throw context, or switch it depending on your use case</td></tr>
  <tr class="msg" id="L3"><td class="ts-cell"><a class="ts" href="#L3" alt="Tue May 28 2024 02:48:43 GMT-0700 (Pacific Daylight Time)">09:48</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-4" title="@abotella:igalia.com">Andreu Botella</span>&gt;</div></td><td class="msg-cell">the same way you'd wrap with a higher-level exception at API boundaries</td></tr>
  <tr class="msg" id="L4"><td class="ts-cell"><a class="ts" href="#L4" alt="Tue May 28 2024 02:48:58 GMT-0700 (Pacific Daylight Time)">09:48</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-4" title="@abotella:igalia.com">Andreu Botella</span>&gt;</div></td><td class="msg-cell">the inner throw context would be an implementation detail</td></tr>
  <tr class="msg" id="L5"><td class="ts-cell"><a class="ts" href="#L5" alt="Tue May 28 2024 02:49:06 GMT-0700 (Pacific Daylight Time)">09:49</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-4" title="@abotella:igalia.com">Andreu Botella</span>&gt;</div></td><td class="msg-cell">am I making sense?</td></tr>
  <tr class="msg" id="L6"><td class="ts-cell"><a class="ts" href="#L6" alt="Tue May 28 2024 02:53:43 GMT-0700 (Pacific Daylight Time)">09:53</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-7" title="@legendecas:matrix.org">Chengzhong Wu</span>&gt;</div></td><td class="msg-cell"><mx-reply><blockquote> the way I think of it, if an exception (or promise rejection) is "automatically rethrown" (as might happen conceptually in <code>run</code>), then if you have a way to act on that error, then that context shouldn't be lost without a trace</blockquote></mx-reply>What's an "automatical rethrown"?</td></tr>
  <tr class="msg" id="L7"><td class="ts-cell"><a class="ts" href="#L7" alt="Tue May 28 2024 02:55:03 GMT-0700 (Pacific Daylight Time)">09:55</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-4" title="@abotella:igalia.com">Andreu Botella</span>&gt;</div></td><td class="msg-cell">well, I was thinking of how <code>run()</code> essentially rethrows a thrown exception, or how a <code>.then()</code> without a catch handler essentially rethrows a promise rejection, without any user code</td></tr>
  <tr class="msg" id="L8"><td class="ts-cell"><a class="ts" href="#L8" alt="Tue May 28 2024 03:14:07 GMT-0700 (Pacific Daylight Time)">10:14</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-7" title="@legendecas:matrix.org">Chengzhong Wu</span>&gt;</div></td><td class="msg-cell"><p>A handled promise could be <code>await</code>-ed or add a new branch with <code>.then</code>, and an <code>unhandledrejection</code> is dispatched for the promise that has no handler instead of the handled rejection source promise.</p>
<pre><code class="language-js">const p1 = asyncVar.run("p1", () =&gt; new Promise((resolve, reject) =&gt; {
  reject('rejection')
}))
p1.then(() =&gt; {}, () =&gt; {}) // handle this promise

const p2 = asyncVar.run("p2", async () =&gt; {
  await p1
})

window.addEventListener("unhandledrejection", event =&gt; {
  event.promise // =&gt; p2
  asyncVar.get() // =&gt; ?
})
</code></pre>
</td></tr>
  <tr class="msg" id="L9"><td class="ts-cell"><a class="ts" href="#L9" alt="Tue May 28 2024 03:36:49 GMT-0700 (Pacific Daylight Time)">10:36</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-7" title="@legendecas:matrix.org">Chengzhong Wu</span>&gt;</div></td><td class="msg-cell"><mx-reply><blockquote> I don't think this is a problem. Context splits are not problematic, only merges are. If you only care about one of the branched promises but not the rest, you could still want to know the source of rejection</blockquote></mx-reply>Like the example above, awaiting a promise of a different context is a merge operation in flow-through</td></tr>
  <tr class="msg" id="L10"><td class="ts-cell"><a class="ts" href="#L10" alt="Tue May 28 2024 03:37:27 GMT-0700 (Pacific Daylight Time)">10:37</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-4" title="@abotella:igalia.com">Andreu Botella</span>&gt;</div></td><td class="msg-cell">I guess both p1 and p2 could be contexts you might want, it's the same pass-around vs pass-through distinction</td></tr>
  <tr class="msg" id="L11"><td class="ts-cell"><a class="ts" href="#L11" alt="Tue May 28 2024 03:38:42 GMT-0700 (Pacific Daylight Time)">10:38</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-7" title="@legendecas:matrix.org">Chengzhong Wu</span>&gt;</div></td><td class="msg-cell">yeah, it could be. I'm saying that the flow-around is not something that is not desired.</td></tr>
  <tr class="msg" id="L12"><td class="ts-cell"><a class="ts" href="#L12" alt="Tue May 28 2024 06:36:54 GMT-0700 (Pacific Daylight Time)">13:36</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-10" title="@littledan:matrix.org">littledan</span>&gt;</div></td><td class="msg-cell"><mx-reply><blockquote> <p>I think the flow-through pattern doesn't answer the similar problem of <a href="https://github.com/tc39/proposal-async-context/issues/90">https://github.com/tc39/proposal-async-context/issues/90</a>.</p>
<p>The originating context could be a stack of contexts and use inner-most context would discard all outer contexts. Each <code>await</code> creates resolution handler on a potentially rejected promise, use the inner-most context would lose the context when the rejection was handled multiple times.</p>
<pre><code class="language-js">let aGlobalPromise = asyncVar.run('global', () =&gt; {
  return Promise.reject()
})

async function someAsyncApi() {
  await asyncVar.run('async-inner', async () =&gt; {
    try {
      await aGlobalPromise
    } catch (e) {
      throw e
    }
  })
}

asyncVar.run("foo", async () =&gt; {
  await someAsyncApi()
});
asyncVar.run("bar", async () =&gt; {
  await someAsyncApi()
});

window.addEventListener("unhandledrejection", () =&gt; {
  console.log(asyncVar.get());  // 'foo' or 'bar' or 'global' or 'async-inner'?
});
</code></pre>
</blockquote></mx-reply>the problem is actually worse than this looks: with any stack of async functions, the unhandled rejection will be credited as throwing from the outermost one, even if there's no catch/finally clause.</td></tr>
  <tr class="msg" id="L13"><td class="ts-cell"><a class="ts" href="#L13" alt="Tue May 28 2024 06:37:45 GMT-0700 (Pacific Daylight Time)">13:37</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-10" title="@littledan:matrix.org">littledan</span>&gt;</div></td><td class="msg-cell">I'm not sure whether the resolve context change would address this; my initial intuition is that it wouldn't</td></tr>
  <tr class="msg" id="L14"><td class="ts-cell"><a class="ts" href="#L14" alt="Tue May 28 2024 06:38:16 GMT-0700 (Pacific Daylight Time)">13:38</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-10" title="@littledan:matrix.org">littledan</span>&gt;</div></td><td class="msg-cell">but maybe the context would be propagated properly through the chain of rejections?</td></tr>
  <tr class="msg" id="L15"><td class="ts-cell"><a class="ts" href="#L15" alt="Tue May 28 2024 07:19:41 GMT-0700 (Pacific Daylight Time)">14:19</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-4" title="@abotella:igalia.com">Andreu Botella</span>&gt;</div></td><td class="msg-cell"><mx-reply><blockquote> but maybe the context would be propagated properly through the chain of rejections?</blockquote></mx-reply>I think with run it would, because if you're awaiting for a promise that rejects, the rejection can't have the context from before the await, so the only possible context for the current async function's promise to reject with is the reject-time context of the awaited promise</td></tr>
  <tr class="msg" id="L16"><td class="ts-cell"><a class="ts" href="#L16" alt="Tue May 28 2024 07:19:51 GMT-0700 (Pacific Daylight Time)">14:19</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-4" title="@abotella:igalia.com">Andreu Botella</span>&gt;</div></td><td class="msg-cell">with set I'm not sure</td></tr>
  <tr class="msg" id="L17"><td class="ts-cell"><a class="ts" href="#L17" alt="Tue May 28 2024 07:40:15 GMT-0700 (Pacific Daylight Time)">14:40</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-10" title="@littledan:matrix.org">littledan</span>&gt;</div></td><td class="msg-cell">with the current semantics of AsyncContext, the outer promise is the one that's the unhandled rejection, and that's outside of the .run calls which might be deeper in the stack</td></tr>
  <tr class="msg" id="L18"><td class="ts-cell"><a class="ts" href="#L18" alt="Tue May 28 2024 07:41:18 GMT-0700 (Pacific Daylight Time)">14:41</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-10" title="@littledan:matrix.org">littledan</span>&gt;</div></td><td class="msg-cell">an alternative would be to store a snapshot when an Error is constructed or first thrown, and then restore that snapshot later, for example, just like how stack traces work</td></tr>
  <tr class="msg" id="L19"><td class="ts-cell"><a class="ts" href="#L19" alt="Tue May 28 2024 08:41:15 GMT-0700 (Pacific Daylight Time)">15:41</a></td><td class="nick-cell"><div class="m-ov">&lt;<span class="nick nick-7" title="@legendecas:matrix.org">Chengzhong Wu</span>&gt;</div></td><td class="msg-cell">20m to the call today, please feel free to add your topics at <a href="https://docs.google.com/document/d/1pi-NMbqVhg2UuxQAZ4jOGDeHLlZGD_DJ7fyxHt_C2hs/edit">https://docs.google.com/document/d/1pi-NMbqVhg2UuxQAZ4jOGDeHLlZGD_DJ7fyxHt_C2hs/edit</a></td></tr>

</tbody></table></div></div></div>
</body></html>